server:
  port: 0
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/appsdeveloperblog
          jwk-set-uri: http://localhost:8080/realms/appsdeveloperblog/protocol/openid-connect/certs
  application:
    name: demo-albums

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    appname: demo-albums
    instance-id: ${spring.application.name}:${instanceId:${random.value}}