server:
  port: 8085
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: http://localhost:8080/realms/appsdeveloperblog
          jwk-set-uri: http://localhost:8080/realms/appsdeveloperblog/protocol/openid-connect/certs